#!/usr/bin/env bash
PROJECT_VERSION="0"
PROJECT_NAME="Stir"
PROJECT_CLIENT="EMRL"
REPO_HOST="http://github.com/EMRL"
REPO="stir"
MASTER="master"
STASH="FALSE"
CHECK_BRANCH="master"
HTML_TEMPLATE="default"
